### ISSUE TITLE
module not working

### ISSUE THREAD

**Issue by fedeb95** [FrogLogics/GodotSQL#1]
I put the directory inside godot/modules, then compiled with scons platform=x11 (my system), but when I run Godot and try to get the singleton I get a null instance. Am I missing something?

**Comment by RameshRavone** [comment]
GodotSql s only for android.

**Comment by RameshRavone** [comment]
usage
```
var sql

if OS.get_name() == "Android":
    sql = Global.get_singleton("SQLBridge")
```

and for usage
```
if sql != null:
    sql.setValue("key", "value")
```
